export const sampleData = [
  {
    name: "Greward",
    title: "Sword for Hire",
    level: 3,
    class: "Fighter",
    race: "Human",
    age: 29,
    gender: "M",
    currentHP: 21,
    hp_by_lvl: "10, 7, 4",
    ac_adj: 0,
    status: "Normal",
    str: 17,
    ex_str: 0,
    intel: 11,
    dex: 15,
    con: 9,
    wis: 12,
    cha: 7,
    spellbookLvl_1: "",
    spellbookLvl_2: "",
    spellbookLvl_3: "",
    spellbookLvl_4: "",
    spellbookLvl_5: "",
    spellbookLvl_6: "",
    spellbookLvl_7: "",
    spellbookLvl_8: "",
    spellbookLvl_9: "",
    memorized: "",
    gold: 250,
    armor: "Plate Mail",
    att_adj: 0,
    weapon: "Longsword",
    items: "",
    probity: 0,
    affiliation: "None",
    notes: "Greward wanders the land as an itinerant swordsman, seeking to fight evil and acquire treasure in equal measure."
  }
]