export const sampleData = [
  {
    name: "Greward",
    title: "Sword for Hire",
    level: 3,
    class: "Fighter",
    race: "Human",
    age: 29,
    gender: "M",
    currentHP: 21,
    hp_by_lvl: "10, 7, 4",
    ac_adj: 0,
    status: "Normal",
    str: 17,
    ex_str: 0,
    intel: 11,
    dex: 15,
    con: 9,
    wis: 12,
    cha: 7,
    gold: 250,
    armor: "Plate Mail",
    att_adj: 0,
    weapon: "Longsword",
    items: "",
    probity: 0,
    affiliation: "None",
    notes: "Greward wanders the land as an itinerant swordsman, seeking to fight evil and acquire treasure in equal measure."
  },
  {
    name: "Shadora",
    title: "The Burninator",
    level: 5,
    class: "Magic-User",
    race: "Human",
    age: 29,
    gender: "F",
    currentHP: 15,
    hp_by_lvl: "4, 2, 3, 2, 4",
    ac_adj: 0,
    status: "Normal",
    str: 10,
    ex_str: 0,
    intel: 17,
    dex: 13,
    con: 14,
    wis: 8,
    cha: 11,
    SBLvl_1: "Burning Hands, Detect Magic, Read Magic, Shield, Spider Climb",
    SBLvl_2: "Detect Invisibility, Pyrotechnics, Web, Wizard Lock",
    SBLvl_3: "Fireball",
    memorized: "Burning Hands, Detect Magic, Read Magic, Shield, Pyrotechnics, Web, Fireball",
    gold: 3706,
    armor: "None",
    att_adj: 0,
    weapon: "Dagger",
    items: "",
    probity: 0,
    affiliation: "Order of the Tome",
    notes: "Shadora studies tirelessly to master the arcane arts and torches whatever gets in her way."
  },
  {
    name: "Skiff",
    title: "Harmless Halfling",
    level: 4,
    class: "Thief",
    race: "Halfling",
    age: 37,
    gender: "O",
    currentHP: 24,
    hp_by_lvl: "6, 2, 3, 5",
    ac_adj: 0,
    status: "Normal",
    str: 8,
    ex_str: 0,
    intel: 14,
    dex: 17,
    con: 16,
    wis: 9,
    cha: 16,
    gold: 1494,
    armor: "None",
    att_adj: 0,
    weapon: "Shortsword",
    items: "",
    probity: 0,
    affiliation: "Sneaky Badger Guild",
    notes: "Skiff never intended to pursue a life of thievery, but it came so naturally they just went with it."
  }
];
